name: musify
description: Music Streaming and Downloading app made in Flutter!
homepage: https://github.com/gokadzev/Musify
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 6.5.2+66 # run update.sh after changing the version

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ^3.13.6

dependencies:
  audio_service: ^0.18.12
  audio_session: ^0.1.16
  background_downloader: ^7.10.1
  cached_network_image: ^3.3.0
  dynamic_color: ^1.6.8
  file_picker: ^6.0.0
  fluentui_system_icons: ^1.1.219
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  just_audio: ^0.9.35
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  receive_sharing_intent:
    path: ./packages/receive_sharing_intent
  rss_dart: ^1.0.4
  rxdart: ^0.27.7
  url_launcher: ^6.1.14
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/db/playlists.db.json
    - assets/fonts/roboto/
    - assets/fonts/paytone/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash.png
  color_dark: '#151515'
  image_dark: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/splash.png
    icon_background_color_dark: '#151515'

flutter_icons:
  android: 'launcher_icon'
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  image_path: 'assets/images/ic_launcher.png'
